// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEmbIz78FfGLr9w3t4fx2hhgnBCIs51NQ',
    appId: '1:655354932359:web:f51ece0b3abdf9610b9c22',
    messagingSenderId: '655354932359',
    projectId: 'cabankapp-f517c',
    authDomain: 'cabankapp-f517c.firebaseapp.com',
    storageBucket: 'cabankapp-f517c.firebasestorage.app',
    measurementId: 'G-YEBWQVYDJ9',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPBD7TPGponoStaJHY0_Xnn_zhIfr3AbQ',
    appId: '1:655354932359:android:f88ce47066c865e60b9c22',
    messagingSenderId: '655354932359',
    projectId: 'cabankapp-f517c',
    storageBucket: 'cabankapp-f517c.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFPZW4lvE7aChICv-VicAeHQ2z_KCaBsA',
    appId: '1:655354932359:ios:03fe2325388a64160b9c22',
    messagingSenderId: '655354932359',
    projectId: 'cabankapp-f517c',
    storageBucket: 'cabankapp-f517c.firebasestorage.app',
    iosBundleId: 'com.test.cabankapplication',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFPZW4lvE7aChICv-VicAeHQ2z_KCaBsA',
    appId: '1:655354932359:ios:03fe2325388a64160b9c22',
    messagingSenderId: '655354932359',
    projectId: 'cabankapp-f517c',
    storageBucket: 'cabankapp-f517c.firebasestorage.app',
    iosBundleId: 'com.test.cabankapplication',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEmbIz78FfGLr9w3t4fx2hhgnBCIs51NQ',
    appId: '1:655354932359:web:5be23f666376b0760b9c22',
    messagingSenderId: '655354932359',
    projectId: 'cabankapp-f517c',
    authDomain: 'cabankapp-f517c.firebaseapp.com',
    storageBucket: 'cabankapp-f517c.firebasestorage.app',
    measurementId: 'G-YCHPDK5MWX',
  );
}
